accept URLs with long Git tag refs
Extends `urlRegex` to accept tags specified with full `refs/tags/*` format.
Note the use of `?:` part to make the group not present in the `matche` list.

The need to reference Git tags with `refs/tags/` prefix is caused by
changes in how Nix `2.4` and newer versions handle Git tags. They expect
tags without full name to be branches, which fails with:
```
fatal: couldn't find remote ref refs/heads/v2.0.3-status-v6
error: program 'git' failed with exit code 128
```

Issue: https://github.com/status-im/status-react/issues/12832
PR: https://github.com/status-im/status-react/pull/12980

Signed-off-by: Jakub Sokołowski <jakub@status.im>